version: '3'
services:
  postgis:
    build: postgis
    #ports:
      #- "5432:5432"

  server:
    build: server
    depends_on:
      - postgis
    ports:
      - "8081:80"

  importer:
    build: importer
    depends_on:
      - postgis
